location_name: 'Traverse Area District Library'
format_options:  [['All Formats', 'fmt' ,'all'], ['Books', 'fmt' ,'a'],['Large Print', 'shelving_location', '534'],['Audiobooks','shelving_location','515,518,546,571,572,582,584,590,597,680,1090'],['eBooks','fmt','ebooks'],['Movies / TV', 'fmt' ,'g'],['Music', 'fmt' ,'j'],['Music - Vinyl','shelving_location','533'],['Video Games','shelving_location','777'],['Board Games', 'shelving_location', '1059'],['STEM Kits', 'shelving_location', '1058'],['Library of Things', 'shelving_location', '1006,1026,514,1112'],['Sheet Music','fmt','notated_music']]
format_label: 'Format'
default_search_display: 'list'
stylesheet: 'tadl.css'
logo_on_homepage: 'true'
homepage_logo: 'large_tadl_logo.png'
search_text: 'Search'
search_menu: 'Search'
tracked: 'true'
has_audience: 'true'
has_chat: true
tracking_code: 'UA-75692003-1'
ga4_code: 'G-EMV7N02VCF'
default_loc: '22'
slider_frequency: 10
has_captcha: true
promote_aspen: true
additional_nav_links:
  - name: 'TADL Website'
    href: 'https://www.tadl.org/'
lists:
  - name: 'tadl_books_list'
    fancy_name: 'New Books'
    search_params: {'loc' : '22',
                    'qtype' : 'shelf',
                    'shelving_location' : ['619','621'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "New Fiction"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=619&search_title=New Fiction'
      - name: "New Non-fiction"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=621&search_title=New Non-fiction'
      - name: "Large Print"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=534&search_title=Large Print'
      - name: "Browsing HOT Titles"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=683&search_title=Browsing HOT Titles'
      - name: "Oversize"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=544&search_title=Oversize'
      - name: "Audiobooks"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=584&shelving_location[]=518&shelving_location[]=515&shelving_location[]=546&shelving_location[]=571&shelving_location[]=572&shelving_location[]=582&&shelving_location[]=590&shelving_location[]=597&&shelving_location[]=680&shelving_location[]=1090&search_title=Audiobooks'
      - name: "Audiobooks on MP3 CD"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=680&search_title=Audiobooks on MP3 CD'
      - name: "Playaways"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=546&shelving_location[]=590&search_title=Playaways'
  - name: 'tadl_movies_list'
    fancy_name: 'New Movies & TV'
    search_params: {'loc' : '22',
                    'qtype' : 'shelf',
                    'shelving_location' : ['687','682'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "Hot DVDs"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=682&search_title=Hot DVDs'
      - name: "New DVDs"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=687&search_title=New DVDs'
      - name: "TC Film Festival"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=778&search_title=TC Film Festival'
      - name: 'Animation'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=g&genres[]=Animation&search_title=Animation&genre_lock=Animation'
      - name: "Educational Television"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=801&search_title=Educational Television'
      - name: "Action/Adventure"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=982&search_title=Action/Adventure'
      - name: 'Family'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=g&genres[]=Family&search_title=Family&genre_lock=Family'
      - name: 'Comedy'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=g&genres[]=Comedy&search_title=Comedy&genre_lock=Comedy'
      - name: "Crime/Mystery"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=985&search_title=Crime/Mystery'
      - name: 'Documentary'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=g&genres[]=Documentary&search_title=Documentary&genre_lock=Documentary'
      - name: "Drama"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=987&search_title=Drama'
      - name: "Avant-Garde"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=983&search_title=Avant-Garde'
      - name: "Family"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=772&search_title=Family'
      - name: "Fantasy"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=989&search_title=Fantasy'
      - name: "Foreign"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=774&search_title=Foreign'
      - name: 'Horror'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=g&genres[]=Horror&search_title=Horror&genre_lock=Horror'
      - name: 'Music'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=g&genres[]=Music&search_title=Music&genre_lock=Music'
      - name: "Musicals"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=821&search_title=Musicals'
      - name: "Opera"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=781&search_title=Opera'
      - name: "Performing Arts"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=997&search_title=Performing Arts'
      - name: 'Romance'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=g&genres[]=Romance&search_title=Romance&genre_lock=Romance'
      - name: 'Science Fiction'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=g&genres[]=Science%20Fiction&search_title=Science%20Fiction&genre_lock=Science%20Fiction'
      - name: 'TV'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=g&genres[]=TV&search_title=TV&genre_lock=TV'
      - name: "British TV"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=1042&search_title=British TV'
      - name: "E-TV"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=801&search_title=E-TV'
      - name: "Thriller"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=995&search_title=Thriller'
      - name: 'Western'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=g&genres[]=Western&search_title=Western&genre_lock=Western'
  - name: 'tadl_music_list'
    fancy_name: 'New Music'
    search_params: {'loc' : '22',
                    'qtype' : 'shelf',
                    'shelving_location' : ['686','684'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "New Music"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=686&search_title=New%20Music'
      - name: "Hot Tunes"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=684&search_title=Hot%20Tunes'
      - name: 'Avant-garde'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Avant-garde&search_title=Avant-garde&genre_lock=Avant-garde'
      - name: 'Blues'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Blues&search_title=Blues&genre_lock=Blues'
      - name: 'Classical'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Classical&search_title=Classical&genre_lock=Classical'
      - name: 'Comedy/Spoken'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&genres[]=Comedy/Spoken&search_title=Comedy/Spoken&genre_lock=Comedy/Spoken'
      - name: 'Country'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Country&search_title=Country&genre_lock=Country'
      - name: 'Easy Listening'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Easy Listening&search_title=Easy Listening&genre_lock=Easy Listening'
      - name: 'Electronic'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Electronic&search_title=Electronic&genre_lock=Electronic'
      - name: 'Folk'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Folk&search_title=Folk&genre_lock=Folk'
      - name: 'International'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=International&search_title=International&genre_lock=International'
      - name: 'Jazz'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Jazz&search_title=Jazz&genre_lock=Jazz'
      - name: 'Latin'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Latin&search_title=Latin&genre_lock=Latin'
      - name: 'Local'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Local&search_title=Local&genre_lock=Local'
      - name: 'New Age'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=New Age&search_title=New Age&genre_lock=New Age'
      - name: 'Opera'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Opera&search_title=Opera&genre_lock=Opera'
      - name: 'Pop/Rock'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Pop/Rock&search_title=Pop/Rock&genre_lock=Pop/Rock'
      - name: 'Rap'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Rap&search_title=Rap&genre_lock=Rap'
      - name: 'Reggae'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Reggae&search_title=Reggae&genre_lock=Reggae'
      - name: 'Religious'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Religious&search_title=Religious&genre_lock=Religious'
      - name: 'Rhythm and Blues'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Rhythm and Blues&search_title=Rhythm and Blues&genre_lock=Rhythm and Blues'
      - name: 'Vocal'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=22&fmt=j&genres[]=Vocal&search_title=Vocal&genre_lock=Vocal'
  - name: 'library_of_things'
    fancy_name: 'Library of Things'
    search_params: {'loc' : '22',
                  'qtype' : 'shelf',
                  'shelving_location' : ['1006','1026','514'],
                  'canned' : 'true',
                  'availability' : 'on',
                  'sort' : 'createDESC'}
has_more_lists: true
more_lists:
  - name: 'games_list'
    fancy_name: 'New Video Games'
    search_params: {'loc' : '23',
                    'qtype' : 'shelf',
                    'shelving_location' : ['777'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: 'Nintendo Switch'
        url: '/main/search?query=GAME SWITCH&qtype=call_number&sort=pubdateDESC&loc=23'
      - name: 'Nintendo Wii'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&genres[]=Nintendo Wii video games.&search_title=Nintendo Wii&genre_lock=Nintendo Wii video games.'  
      - name: "Nintendo Wii U"
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&genres[]=Nintendo Wii U video games.&search_title=Nintendo Wii U&genre_lock=Nintendo Wii U video games.'
      - name: 'Nintendo 3DS'
        url: '/main/search?query=GAME 3DS&qtype=call_number&sort=pubdateDESC&loc=23'
      - name: 'PlayStation 5'
        url: '/main/search?query=GAME%20PS5&qtype=call_number&sort=pubdateDESC&loc=23'
      - name: 'PlayStation 4'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&genres[]=PlayStation 4 video games.&search_title=PlayStation 4&genre_lock=PlayStation 4 video games.'
      - name: 'PlayStation 3'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&genres[]=PlayStation 3 video games.&search_title=PlayStation 3&genre_lock=PlayStation 3 video games.'
      - name: 'PlayStation 2'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&genres[]=PlayStation 2 video games.&search_title=PlayStation 2&genre_lock=PlayStation 2 video games.'
      - name: 'Xbox One'
        url: '/main/search?query=GAME XBOXONE&qtype=call_number&sort=pubdateDESC&loc=23'
      - name: "Xbox 360"
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&genres[]=Xbox 360 video games.&search_title=Xbox 360&genre_lock=Xbox 360 video games.'
      - name: 'Xbox'
        url: '/main/search?query=&qtype=genre&sort=pubdateDESC&loc=23&genres[]=Xbox video games.&search_title=Xbox&genre_lock=Xbox video games.'
  - name: 'audiobooks_list'
    fancy_name: 'New Audiobooks'
    search_params: {'loc' : '22',
                    'qtype' : 'shelf',
                    'shelving_location' : ['515','518','546','571','572','582','584','590','597','680','1090'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}
    searches:
      - name: "Audiobooks"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=584&shelving_location[]=518&shelving_location[]=515&shelving_location[]=546&shelving_location[]=571&shelving_location[]=572&shelving_location[]=582&&shelving_location[]=590&shelving_location[]=597&&shelving_location[]=680&shelving_location[]=1090&search_title=Audiobooks'
      - name: "Audiobooks on MP3 CD"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=680&search_title=Audiobooks on MP3 CD'
      - name: "Playaways"
        url: '/main/search?query=&qtype=shelf&sort=pubdateDESC&loc=22&shelving_location[]=546&shelving_location[]=590&search_title=Playaways'
  - name: 'STEM_Kits_list'
    fancy_name: 'STEM Kits'
    search_params: {'loc' : '22',
                    'qtype' : 'shelf',
                    'shelving_location' : ['1058'],
                    'canned' : 'true',
                    'availability' : 'on',
                    'sort' : 'pubdateDESC'}